# Site settings
title: AndysBlong
email: andsinlight@163.com
description: > # this means to ignore newlines until "baseurl:"
 欢迎访问我的博客！
baseurl: "" # the subpath of your site, e.g. /blog/
#safe:false
url: "http://yourdomain.com" # the base hostname & protocol for your site
/*twitter_username: jekyllrb
/*github_username:  jekyll

# Build settings
markdown: kramdown
#baseurl: /StrayBirdsmarkdown: redcarpetsafe: falsepygments: trueexcerpt_separator: "\n\n\n"paginate: 5
